### ISSUE TITLE
Encapsulate global parameters and free functions in a namespace

### ISSUE THREAD

**Issue by KriSun95** [foxsi/foxsi-4matter#30]
The following files

- foxsi-4matter/include/Parameters.h
- foxsi-4matter/include/Utilities.h
- foxsi-4matter/include/Utilities.cpp

contain variable and function declarations in the global scope—they are not part of any class. It would be safer to wrap all of these in a namespace. Then, instead of referring to the `SPACEWIRE_ADDRESS_LENGTH` variable, we could do `parameters::SPACEWIRE_ADDRESS_LENGTH` or something. Same thing for the functions in `Utilities.h`.

So the todo items for this task:

- [x] Come up with ways to clump the parameters and utilities that make sense (Ethernet stuff, SpaceWire stuff, etc could be grouped)
- [x] Put each clump in its own namespace
- [x] Refactor the rest of the code to use the namespace::name instead of just the bare variable/function name.

*From Thanasi's Google Doc*

**Comment by yixianz** [comment]
Addressed in #37
