### ISSUE TITLE
Write a synchronous UART sender

### ISSUE THREAD

**Issue by KriSun95** [foxsi/foxsi-4matter#32]
Need a Raspberry Pi for this. Pretty much just find a way to open a UART port (find a UART library, first) and send bytes out of it. You can do a loopback test on a single Pi where you connect a UART TX pin to the same port’s RX pin and verify you can read what you’re sending out.

*From Thanasi's Google Doc*

**Comment by thanasipantazides** [comment]
Kris implemented!
