### ISSUE TITLE
Write an asynchronous UART listener

### ISSUE THREAD

**Issue by KriSun95** [foxsi/foxsi-4matter#34]
This is tied to #32 and then, by extension, #33.

After launch we will receive uplink commands over UART. We want to catch these anytime they arrive using an asynchronous listener. We also want to receive data from Timepix over UART. Can you perform a synchronous UART read call (from some TBD UART library for Pi) from a function that has been posted (assigned as work) to a `boost::asio::io_context`?  

*From Thanasi's Google Doc*

**Comment by thanasipantazides** [comment]
This is addressed by `boost::asio::serial_port` introduced (minimally) in [c7a976a](https://github.com/foxsi/foxsi-4matter/commit/c7a976abbeda8d780dfa8e474d2ea140ea2c2b1d). Closing.
